name: edt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # dart run easy_localization:generate -f keys -o locale_keys.dart -O lib/src/constants -S assets/translation
  easy_localization: ^3.0.5
  flex_color_scheme: ^7.3.1

  supabase_flutter: ^2.5.1
  supabase_auth_ui: ^0.4.4

  go_router: ^13.2.4

  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/translation/