name: edt
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # dart run easy_localization:generate -f keys -o locale_keys.dart -O lib/src/constants -S assets/translation
  easy_localization: ^3.0.6
  flex_color_scheme: ^7.3.1

  supabase_flutter: ^2.5.1
  supabase_auth_ui: ^0.4.4

  go_router: ^13.2.4

  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:
  freezed_annotation:
  json_annotation:

  image_picker_widget: ^2.4.1
  flutter_gravatar: ^2.0.2
  fancy_shimmer_image: ^2.0.3
  cached_network_image: ^3.3.1
  toastification: ^1.2.1
  shimmer: ^3.0.0

  flutter_form_builder: ^9.2.1
  form_builder_validators: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
  assets:
    - assets/translation/

scripts:
  translate: dart run easy_localization:generate -f keys -o locale_keys.dart -O lib/src/constants -S assets/translation