name: Deploy Web-App to Github-Pages
"on":
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      # run any `bun` or `bunx` command
      - name: Install Dependencies
        uses: bun install

      - name: Deploy Web-App
        uses: bun run deploy
